const books=[
 {id:1,title:'إتقان الكود',author:'بايت بوكس',price:399,category:'تكنولوجيا',image:'images/BOOK1.png',description:'مرجع عملي للمطورين الباحثين عن أساليب برمجية أوضح وأفضل، مع أمثلة من واقع الحياة.'},
 {id:2,title:'طريق العلم',author:'جون كارتر',price:499,category:'تكنولوجيا',image:'images/BOOK2.png',description:'رحلة مبسطة وممتعة لاكتشاف العلوم والأفكار التي تصنع عالمنا.'},
 {id:3,title:'العقلية تهم',author:'روبن شارما',price:299,category:'إدارة',image:'images/4cc63f92c5e11e6750073d169e4a4223.jpg',description:'خطوات عملية لبناء عقلية أكثر تركيزًا وتحويل العادات اليومية إلى نتائج ملموسة.'},
 {id:4,title:'الربح من التسويق',author:'جاي شيتي',price:499,category:'إدارة',image:'images/76c383554fcce0b43d506a7744b0926f.jpg',description:'دليل معاصر لفهم التسويق وبناء قيمة حقيقية تصل إلى جمهورك.'},
 {id:5,title:'عادات ذرية',author:'جيمس كلير',price:549,category:'أدب',image:'images/85f81d008146d8a0f73568fee61ac734.jpg',description:'كيف تصنع تغييرات صغيرة مستمرة تقودك إلى نتائج كبيرة ومستدامة.'},
 {id:6,title:'الكتابة الإبداعية',author:'ووردبريس برس',price:299,category:'أدب',image:'images/c142719d8ee2f05b9f02194e7510e61f.jpg',description:'دليل ملهم لكل من يريد أن يكتب بقلب واضح وصوت مميز.'}
];
const get=(key)=>JSON.parse(localStorage.getItem(key)||'[]');
const set=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const money=(v)=>`${Number(v).toLocaleString('ar-YE')} RY`;
const toast=(message)=>{const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)};
const findBook=(id)=>books.find(b=>b.id===Number(id));
function updateCounts(){const cart=document.getElementById('cartCount');const wish=document.getElementById('wishlistCount');if(cart){const count=get('cart').reduce((n,x)=>n+x.qty,0);cart.textContent=count?count:''}if(wish){const count=get('wishlist').length;wish.textContent=count?count:''}}
function addCart(id){const cart=get('cart');const item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({id,qty:1});set('cart',cart);updateCounts();toast('تمت إضافة الكتاب إلى السلة')}
function toggleWish(id){let list=get('wishlist');if(list.includes(id)){list=list.filter(x=>x!==id);toast('تمت الإزالة من المفضلة')}else{list.push(id);toast('تمت الإضافة إلى المفضلة')}set('wishlist',list);updateCounts();renderBooks();renderWishlist()}
function bookCard(book){const wished=get('wishlist').includes(book.id);return `<div class="col-sm-6 col-lg-4"><article class="book-card"><img src="${book.image}" alt="${book.title}"><div class="card-body"><h3>${book.title}</h3><div class="author">${book.author} · ${book.category}</div><div class="price">${money(book.price)}</div><div class="card-actions"><button class="btn btn-primary flex-grow-1 add-cart" data-id="${book.id}">إضافة للسلة</button><button class="icon-btn ${wished?'active':''}" title="المفضلة" data-wish="${book.id}"><i class="bi bi-heart${wished?'-fill':''}"></i></button><button class="icon-btn" title="التفاصيل" data-detail="${book.id}"><i class="bi bi-arrow-left"></i></button></div></div></article></div>`}
function renderBooks(list=books){const grid=document.getElementById('bookGrid');if(!grid)return;grid.innerHTML=list.length?list.map(bookCard).join(''):'<div class="col-12"><div class="alert alert-light">لم نجد كتبًا مطابقة لبحثك.</div></div>'}
function renderWishlist(){const target=document.getElementById('wishlistItems');if(!target)return;const list=get('wishlist').map(findBook).filter(Boolean);target.innerHTML=list.length?list.map(bookCard).join(''):'<div class="col-12"><div class="alert alert-light">قائمة المفضلة فارغة. أضف الكتب التي أعجبتك من قسم الكتب.</div></div>'}
function renderCart(){const cart=get('cart');const target=document.getElementById('cartItems');if(!target)return;target.innerHTML=cart.length?cart.map(({id,qty})=>{const b=findBook(id);return `<div class="cart-row"><img src="${b.image}" alt="${b.title}"><div class="grow"><h3>${b.title}</h3><p>${b.author}</p><strong class="text-orange">${money(b.price)}</strong></div><input class="form-control cart-qty" type="number" min="1" value="${qty}" data-id="${b.id}" style="width:76px"><button class="btn btn-sm btn-outline-danger remove-cart" data-id="${b.id}">حذف</button></div>`}).join(''):'<div class="alert alert-light">السلة فارغة. <a href="#books" class="text-orange">تصفح الكتب الآن</a></div>';const sub=cart.reduce((n,x)=>n+findBook(x.id).price*x.qty,0);document.getElementById('subtotal').textContent=money(sub);document.getElementById('shipping').textContent=money(sub?50:0);document.getElementById('total').textContent=money(sub+(sub?50:0));document.getElementById('cartSummary').textContent=`${cart.reduce((n,x)=>n+x.qty,0)} منتجات`}
function showDetail(id){const b=findBook(id);if(!document.getElementById('detailContent')){location.href=`book-detail.html?id=${id}`;return}document.getElementById('detailContent').innerHTML=`<div class="row g-5 align-items-center"><div class="col-lg-5"><img class="detail-img" src="${b.image}" alt="${b.title}"></div><div class="col-lg-7 detail-content"><span class="eyebrow">تفاصيل الكتاب</span><h2>${b.title}</h2><p class="muted">بواسطة ${b.author}</p><div class="text-warning mb-3">★★★★★ <small class="muted">(245 مراجعة)</small></div><div class="price mb-3">${money(b.price)}</div><p class="lead text-muted">${b.description}</p><div class="d-flex gap-2 mt-4"><button class="btn btn-primary add-cart" data-id="${b.id}">إضافة إلى السلة</button><button class="btn btn-outline-dark" data-wish="${b.id}">إضافة للمفضلة</button></div></div></div>`;document.getElementById('book-detail').classList.remove('d-none');document.getElementById('books').classList.add('d-none');location.hash='book-detail'}
function filterBooks(){const q=document.getElementById('searchInput').value.toLowerCase();let list=books.filter(b=>(b.title+b.author+b.category).toLowerCase().includes(q));const sort=document.getElementById('sortSelect').value;if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);renderBooks(list)}
document.addEventListener('click',e=>{const cart=e.target.closest('.add-cart');if(cart)addCart(Number(cart.dataset.id));const wish=e.target.closest('[data-wish]');if(wish)toggleWish(Number(wish.dataset.wish));const detail=e.target.closest('[data-detail]');if(detail)showDetail(Number(detail.dataset.detail));const remove=e.target.closest('.remove-cart');if(remove){set('cart',get('cart').filter(x=>x.id!==Number(remove.dataset.id)));renderCart();updateCounts()}if(e.target.id==='backToBooks'){document.getElementById('book-detail').classList.add('d-none');document.getElementById('books').classList.remove('d-none');location.hash='books'}if(e.target.id==='checkoutBtn'){toast('تم تجهيز طلبك بنجاح')}const category=e.target.closest('[data-filter]');if(category){document.getElementById('searchInput').value=category.dataset.filter;filterBooks()}});
document.addEventListener('change',e=>{if(e.target.matches('.cart-qty')){const cart=get('cart');const item=cart.find(x=>x.id===Number(e.target.dataset.id));item.qty=Math.max(1,Number(e.target.value));set('cart',cart);renderCart();updateCounts()}});
document.getElementById('searchInput')?.addEventListener('input',filterBooks);document.getElementById('sortSelect')?.addEventListener('change',filterBooks);document.getElementById('loginForm')?.addEventListener('submit',e=>{e.preventDefault();toast('تم تسجيل الدخول تجريبيًا')});document.getElementById('contactForm')?.addEventListener('submit',e=>{e.preventDefault();toast('تم إرسال رسالتك بنجاح');e.target.reset()});
if(document.getElementById('detailContent')){const id=new URLSearchParams(location.search).get('id');if(id)showDetail(Number(id))}
renderBooks();renderWishlist();renderCart();updateCounts();


const navSections=[...document.querySelectorAll('main section[id]')];
const currentPage=location.pathname.split('/').pop()||'index.html';
document.querySelectorAll('.section-nav a.nav-link').forEach(link=>{const href=link.getAttribute('href');if(href===currentPage||(currentPage==='index.html'&&href==='index.html'))link.classList.add('active')});
const navLinks=[...document.querySelectorAll('.main-menu .nav-link')];
const anchorSections=navSections.filter(section=>document.querySelector(`.section-nav a[href=\"#${section.id}\"]`));
if(anchorSections.length){const navObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){navLinks.forEach(link=>{if(link.getAttribute('href')?.startsWith('#'))link.classList.toggle('active',link.getAttribute('href')==='#'+entry.target.id)})}}),{rootMargin:'-28% 0px -62% 0px',threshold:0});anchorSections.forEach(section=>navObserver.observe(section));}
